# Copyright (c) 2020-2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

---
- name: Add Repository Key
  become: yes
  apt_key:
    url: "{{ nvidia_docker_gpg }}"
    state: present

- name: Add Repository Source
  become: yes
  get_url:
    url: "{{ nvidia_docker_repo_src }}"
    dest: "{{ nvidia_docker_repo_dst }}"
    owner: root
    group: root
    mode: 0644

- name: Install Nvidia Docker 2
  become: yes
  apt: name=nvidia-docker2 state=latest update_cache=yes
  register: nvidia_docker_install

- name: Update daemon.json with NVIDIA as Default Runtime
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Reload Docker Configuration
  become: yes
  service: name=docker state=reloaded
  when: nvidia_docker_install.changed == True