# Copyright (c) 2020-2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

---
- name: Add package ca-certificates before adding GPG keys
  become: yes
  apt:
    name: ca-certificates
    update_cache: yes
    state: present

- name: Add apt package apt-transport-https before adding GPG keys
  become: yes
  apt:
    name: apt-transport-https
    update_cache: yes
    state: present

- name: Add Docker CE GPG Apt Key (Ubuntu)
  become: yes
  when: "ansible_lsb.release=='18.04'"
  apt_key:
    url: "{{ docker_ce_gpg }}"
    state: present

- name: Add Docker CE Repository (Bionic)
  become: yes
  when: ansible_lsb.release=='18.04'
  apt_repository:
    repo: "{{ docker_ce_repo_bionic }}"
    state: present

- name: Update apt and Install Docker CE on Bionic
  become: yes
  apt: 
    update_cache: yes 
    name: docker.io
    state: latest
    install_recommends: yes
  when: "ansible_lsb.release=='18.04'"

- name: Update apt and Install Docker.io on Focal
  become: yes
  apt: 
    update_cache: yes 
    name: docker.io
    state: latest
    install_recommends: yes
  when: "ansible_lsb.release=='20.04'"

- name: Add the user to Docker group
  user:
    name: "{{ clara_user }}"
    groups: 
      - docker
    append: yes