# Copyright 2021 NVIDIA Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Ubuntu Install Tasks
  include_tasks: install-ubuntu-driver.yml
  when: ansible_distribution == "Ubuntu"

- name: Add Profile Script to Set Environment for Toolkit
  copy:
    src: "cuda-vars.sh"
    dest: "/etc/profile.d/cuda-vars.sh"
    owner: "root"
    group: "root"
    mode: "0644"
  when: cuda_toolkit_add_profile_script
