# Copyright 2021 NVIDIA Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Remove Any Existing Clara CLI Packages
  shell: rm -rf clara_cli*
  args:
    chdir: /tmp

- name: Download Latest Clara CLI
  command: ngc registry resource download-version {{ngc_org}}/{{ngc_team}}/{{cli_target}}
  args:
    chdir: /tmp
  become_user: '{{ clara_user }}'


- name: Unarchive Clara CLI Package
  shell: find clara_cli* | grep cli.zip | xargs -I {} unzip {} -d clara_cli
  args:
    chdir: /tmp

- name: Find Clara CLI Binaries
  find:
    paths: [ "/tmp/clara_cli" ]
    patterns: 'clara*'
    file_type: file
  register: clara_cli_binaries

- name: Copy Clara CLI Binaries to Path
  copy:
    src: '{{item.path}}'
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  with_items: '{{clara_cli_binaries.files}}'
  become: yes

- name: Confirm Clara CLI is Installed Present
  command: which clara
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Configure Clara CLI with NGC Credentials and Org/Team
  command: "clara config -y --key {{ ngc_api_key }} --orgteam '{{ ngc_org }}/{{ ngc_team }}' --verbose"
  become: false
  become_user: '{{ clara_user }}'

- name: Check Clara CLI Configuration
  stat:
    path: "/home/{{ clara_user }}/.clara"
  register: stat_result
  failed_when: not stat_result.stat.exists
  